In [3]:
import numpy
numpy.__version__

'1.17.2'

In [4]:
import scipy
scipy.__version__

'1.3.1'

In [5]:
import pandas
pandas.__version__

'0.25.1'

In [6]:
import matplotlib
matplotlib.__version__

'3.1.1'

# Машинное обучение и анализ данных

## Математика и Python

Задание 1

In [7]:
import pandas as pd

In [8]:
frame = pd.DataFrame({'num':range(10), 'chars':['a']*10})

In [9]:
frame

num chars
0    0     a
1    1     a
2    2     a
3    3     a
4    4     a
5    5     a
6    6     a
7    7     a
8    8     a
9    9     a

In [10]:
new_line = {'num':'7,5', 'chars':'b'}

In [11]:
frame = frame.append(new_line, ignore_index=True)

In [12]:
frame

num chars
0     0     a
1     1     a
2     2     a
3     3     a
4     4     a
5     5     a
6     6     a
7     7     a
8     8     a
9     9     a
10  7,5     b

In [13]:
frame['another col'] = [i+10 for i in range(11)]

In [14]:
frame

num chars  another col
0     0     a           10
1     1     a           11
2     2     a           12
3     3     a           13
4     4     a           14
5     5     a           15
6     6     a           16
7     7     a           17
8     8     a           18
9     9     a           19
10  7,5     b           20

In [15]:
frame.drop([9,10], axis = 0, inplace = True)

In [16]:
frame 

num chars  another col
0   0     a           10
1   1     a           11
2   2     a           12
3   3     a           13
4   4     a           14
5   5     a           15
6   6     a           16
7   7     a           17
8   8     a           18

In [17]:
frame.drop('another col', axis = 1, inplace = True)

In [18]:
frame

num chars
0   0     a
1   1     a
2   2     a
3   3     a
4   4     a
5   5     a
6   6     a
7   7     a
8   8     a

In [19]:
frame.to_csv('frame_file.csv', sep=',', header=True, index=None)

In [20]:
!cat frame_file.csv

num,chars
0,a
1,a
2,a
3,a
4,a
5,a
6,a
7,a
8,a


In [21]:
frame = pd.read_csv('_62e88c592115ea3459114560893e5ef6_dataset.tsv', sep='\t', header=0)

FileNotFoundError: [Errno 2] File b'_62e88c592115ea3459114560893e5ef6_dataset.tsv' does not exist: b'_62e88c592115ea3459114560893e5ef6_dataset.tsv'

In [ ]:
frame.dtypes

In [22]:
frame

num chars
0   0     a
1   1     a
2   2     a
3   3     a
4   4     a
5   5     a
6   6     a
7   7     a
8   8     a

In [23]:
frame.Birth = frame.Birth.apply(pd.to_datetime)

AttributeError: 'DataFrame' object has no attribute 'Birth'

In [24]:
frame

num chars
0   0     a
1   1     a
2   2     a
3   3     a
4   4     a
5   5     a
6   6     a
7   7     a
8   8     a

In [25]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9 entries, 0 to 8
Data columns (total 2 columns):
num      9 non-null object
chars    9 non-null object
dtypes: object(2)
memory usage: 216.0+ bytes


In [26]:
frame.fillna('', inplace=True)

In [27]:
frame

num chars
0    0     a
1    1     a
2    2     a
3    3     a
4    4     a
5    5     a
6    6     a
7    7     a
8    8     a

In [28]:
frame.Position

AttributeError: 'DataFrame' object has no attribute 'Position'

In [29]:
frame[['Name','Position']][1:4]

KeyError: "None of [Index(['Name', 'Position'], dtype='object')] are in the [columns]"

In [30]:
frame.loc[[1,3,5],['Name', 'City']]

KeyError: "None of [Index(['Name', 'City'], dtype='object')] are in the [columns]"

In [31]:
frame.iloc[[1,3,5], [0,2]]

IndexError: positional indexers are out-of-bounds

In [32]:
frame[(frame.Birth >= pd.datetime(1985,1,1)) & (frame.City == 'Москва')]

AttributeError: 'DataFrame' object has no attribute 'Birth'

In [33]:
frame.size

18

In [34]:
frame['123'] = 1,2,3,4,5,6

ValueError: Length of values does not match length of index

In [35]:
frame

num chars
0    0     a
1    1     a
2    2     a
3    3     a
4    4     a
5    5     a
6    6     a
7    7     a
8    8     a

In [36]:
import numpy as np

In [37]:
type([5, 5])

list

In [38]:
a = np.random.rand(4,5)

In [39]:
type(a)

numpy.ndarray

In [40]:
a[3:4]

array([[0.93487067, 0.85791815, 0.18378421, 0.60188468, 0.69787559]])

In [41]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9 entries, 0 to 8
Data columns (total 2 columns):
num      9 non-null int64
chars    9 non-null object
dtypes: int64(1), object(1)
memory usage: 536.0+ bytes


In [42]:
import numpy as np

In [43]:
np.dot([1,2,3],[-3,1,1])

2

In [44]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [45]:
a = np.array([0, -1, 11])
b = np.array([3, 7, 2])
np.dot(a,b)

15

In [46]:
b.dot(a)

15

In [47]:
a*b

array([ 0, -7, 22])

In [48]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
a = np.arange(0,24,2).reshape(3,4)

In [50]:
a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [51]:
a = np.array([[1, 0], [1, 1]])
b = np.array([[4, 1],[3,4]])

In [52]:
print(a,"\n\n",b)

[[1 0]
 [1 1]] 

 [[4 1]
 [3 4]]


In [53]:
b.dot(a)

array([[5, 1],
       [7, 4]])

In [54]:
a.dot(b)

array([[4, 1],
       [7, 5]])

In [55]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])

In [56]:
print (np.linalg.matrix_rank(m) == m.shape[0])

True


In [57]:
np.linalg.det(m)

-1.0

In [58]:
np.arange(1,13,2).reshape((3,2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [59]:
np.eye(4,5)[[0,3],[1,3]]

array([0., 1.])

In [75]:
a = np.array([8, 10, -1, 0, 0])

In [68]:
a.reshape((5,1))

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [76]:
a[np.newaxis,:]

array([[ 8, 10, -1,  0,  0]])

In [77]:
a = numpy.array([0, -1, 11])
b = numpy.array([3, 7, 2])
a*b

array([ 0, -7, 22])

In [6]:
p1=0.49
p2=0.38
p3=0.1
p4=0.03


p1**2 + p2*(p1 + p2) + p3*(p1 + p3) + p4*(p1 + p2 + p3 + p4)

0.6597

In [7]:
2 * 0.8**9

0.2684354560000001

In [2]:
0.01 * (0.8*(100-9.6)/100) * 100

0.7232000000000001

In [3]:
9/36

0.25

In [2]:
import math
M = 1197.69
D = 116182.2

In [3]:
M + math.sqrt(D)*3

2220.2553035381166

In [12]:
sigma = math.sqrt(D/131)
sigma

29.780648463402596

In [10]:
M + 3 * sigma

1287.0319453902077

In [12]:
import math
sum = 0
for i in range(5):
    sum += 3 ** i / math.factorial(i) * pow(math.e, -3)
1 - sum

0.1847367554762278